# Generated by Django 3.0.3 on 2020-02-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('phoneNo', models.CharField(blank=True, max_length=13)),
                ('sex', models.CharField(blank=True, max_length=6)),
                ('subcity', models.CharField(blank=True, max_length=20)),
                ('woreda', models.IntegerField(blank=True)),
                ('nationality', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
